### ISSUE TITLE
can u please share the code for Detectron for distance calculations?

### ISSUE THREAD

**Issue by alfarqi** [MuhammadMoinFaisal/yolov7-segmentation-with-DeepSORT-Tracking#2]
Hi,
i am sorry that i dont know how to reach you, but I am interested in distance calculation with yolo7...can you please share the code that you have created in the video

**Comment by MuhammadMoinFaisal** [comment]
HI I have added the  notebook file i used to implement the Instance Segmentation with Distance Estimation and it is provided in the github repo by the name YOLOv7 Instance Segmentation with Distance Estimation please check it and if you find helpful please give a star

Thanks

**Comment by alfarqi** [comment]
thanks for your quick response, i searched but couldn't find real with this given title "YOLOv7 Instance Segmentation with Distance Estimation"...can you please share the link

**Comment by MuhammadMoinFaisal** [comment]
Hi Alfraqi, the file name is 
Single_Click_YOLOv7_Instance_Segmentation_withDistance_Estimation.ipynb

and here is the link 

https://github.com/MuhammadMoinFaisal/yolov7-segmentation-with-DeepSORT-Tracking/blob/main/Single_Click_YOLOv7_Instance_Segmentation_withDistance_Estimation.ipynb


Thanks

**Comment by alfarqi** [comment]
Thank you brother, Allah bless you for your support

**Comment by MuhammadMoinFaisal** [comment]
Thanks a lot, Happy to help you, if you find this work helpful, please do give this repo a star
